
val IMPL = listOf(
//            "com.github.streamline-essentials:BukkitOfUtils:master-fd112253ce-1",
    "com.github.server-utilities:TheBase:master-SNAPSHOT",
    "dev.folia:folia-api:1.20.4-R0.1-SNAPSHOT",
    "org.spigotmc:spigot-api:1.20.4-R0.1-SNAPSHOT",
    "com.github.hamza-cskn.obliviate-invs:core:4.1.12",
    "net.kyori:adventure-api:4.16.0",
    "net.kyori:adventure-text-serializer-gson:4.16.0",
    "net.kyori:adventure-text-serializer-legacy:4.16.0",
    "net.kyori:adventure-text-serializer-plain:4.16.0",
    "net.kyori:adventure-text-minimessage:4.16.0",
    "net.kyori:adventure-text-serializer-ansi:4.16.0",
    "net.kyori:ansi:1.0.3",
)
val SHADOW = listOf(
//            "com.github.streamline-essentials:BukkitOfUtils:master-fd112253ce-1",
    "com.github.server-utilities:TheBase:master-SNAPSHOT",
    "org.pf4j:pf4j:3.10.0",
    "org.projectlombok:lombok:1.18.30",
    "commons-codec:commons-codec:1.5",
    "org.xerial:sqlite-jdbc:3.45.1.0",
    "mysql:mysql-connector-java:5.1.6",
    "com.github.hamza-cskn.obliviate-invs:core:4.1.12",
    "net.kyori:adventure-api:4.16.0",
    "net.kyori:adventure-text-serializer-gson:4.16.0",
    "net.kyori:adventure-text-serializer-legacy:4.16.0",
    "net.kyori:adventure-text-serializer-plain:4.16.0",
    "net.kyori:adventure-text-minimessage:4.16.0",
    "net.kyori:adventure-text-serializer-ansi:4.16.0",
    "net.kyori:ansi:1.0.3",
)
val ANNO = listOf(
//            "com.github.streamline-essentials:BukkitOfUtils:master-fd112253ce-1",
    "com.github.server-utilities:TheBase:master-SNAPSHOT",
    "org.pf4j:pf4j:3.10.0",
    "org.projectlombok:lombok:1.18.30",
    "commons-codec:commons-codec:1.5",
    "org.xerial:sqlite-jdbc:3.45.1.0",
    "mysql:mysql-connector-java:5.1.6",
    "dev.folia:folia-api:1.20.4-R0.1-SNAPSHOT",
    "org.spigotmc:spigot-api:1.20.4-R0.1-SNAPSHOT",
    "com.github.hamza-cskn.obliviate-invs:core:4.1.12",
    "net.kyori:adventure-api:4.16.0",
    "net.kyori:adventure-text-serializer-gson:4.16.0",
    "net.kyori:adventure-text-serializer-legacy:4.16.0",
    "net.kyori:adventure-text-serializer-plain:4.16.0",
    "net.kyori:adventure-text-minimessage:4.16.0",
    "net.kyori:adventure-text-serializer-ansi:4.16.0",
    "net.kyori:ansi:1.0.3",
)
val COMP_ONLY = listOf(
//            "com.github.streamline-essentials:BukkitOfUtils:master-fd112253ce-1",
    "com.github.server-utilities:TheBase:master-SNAPSHOT",
    "org.pf4j:pf4j:3.10.0",
    "org.projectlombok:lombok:1.18.30",
    "commons-codec:commons-codec:1.5",
    "org.xerial:sqlite-jdbc:3.45.1.0",
    "mysql:mysql-connector-java:5.1.6",
    "dev.folia:folia-api:1.20.4-R0.1-SNAPSHOT",
    "org.spigotmc:spigot-api:1.20.4-R0.1-SNAPSHOT",
    "com.github.hamza-cskn.obliviate-invs:core:4.1.12",
    "net.kyori:adventure-api:4.16.0",
    "net.kyori:adventure-text-serializer-gson:4.16.0",
    "net.kyori:adventure-text-serializer-legacy:4.16.0",
    "net.kyori:adventure-text-serializer-plain:4.16.0",
    "net.kyori:adventure-text-minimessage:4.16.0",
    "net.kyori:adventure-text-serializer-ansi:4.16.0",
    "net.kyori:ansi:1.0.3",
)
//    val FILES = listOf(
////            rootProject.rootDir.getPath().toString() + "impl/sqlite-jdbc.jar"
//    )
val OTHER_PLUGINS = listOf(
    "me.clip:placeholderapi:2.11.5",
)