# Database settings.
database:
  type: SQLITE # MYSQL or SQLITE
  host: "localhost" # Only for MySQL
  port: "3306" # Only for MySQL
  database: "database" # Only for MySQL
  username: "username" # Only for MySQL
  password: "password" # Only for MySQL
  options: "useSSL=false" # Only for MySQL
  table-prefix: "pnts_"
  sqlite-file: "points.db" # Only for SQLite

arenas:
    # Arena identifier
    arena1:
      name: "Arena 1"
      # Radius of the arena
      radius:
        center:
          x: 0.0
          z: 0.0
        start: 249.5
        end: 9.5
        shrink-time: 36000
      lobby:
        world: "world"
        x: 0.0
        y: 0.0
        z: 0.0
        yaw: 0.0
        pitch: 0.0
      # 20 ticks = 1 second
      # 20 * 60 * 2 = 2400 ticks
      grace-period: 2400
      items:
        - "{id: 'minecraft:cooked_beef', count: 8}"
      seeds:
        - 24190412909394
      # 20 ticks = 1 second
      # 20 * 15 = 300 ticks
      ticks-per-layer: 300
      # Reset settings.
      reset:
        # Reset on unload?
        on-unload: true