name: '${name}'
version: '${version}'
main: '${main}'
authors: [ Drak ]
depend:
  - BukkitOfUtils
folia-supported: true

commands:
  lavatized:
    description: Main command for Lavatized.
    permission: lavatized.command.default
    aliases:
      - lavatize
      - lt